// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int count = Integer.parseInt(args[0]);
		int over = 0;
		int under = 0;
		for (int i = 0; i<=count-1; i++){ //create random number and add to counters as needed
			double num = Math.random();
			if (num > 0.5){
				over +=1;
			} else {
				under +=1;
			}
		}
		System.out.println("> 0.5:  " + over + " times");
		System.out.println("<= 0.5: " + under + " times");
		if (over>0 && under>0){ //check if ratio is possible amd print it as needed
			double ratio = (over < under) ? (((double)over)/under) : (((double)under)/over);
			System.out.println("Ratio:" + ratio);
		}		
	}
}

